
= Functional Mapping

*Identification of functional areas and their mapping to domain areas.*

The Exploitation Platform architecture is defined by services that together provide the complete functionality of the platform. Domain Areas are defined as groupings of related services, which provide the building blocks for the system. Dedicated specialist expertise can then be applied to each domain area to ensure the best design and development across the system. Inevitably, there will be some services that stradle the notional divide between domain area - in which case close collaboration is essential between domain area experts to establish a holistic solution.

The identified domain areas are as follows:

User Management (UM)::
All aspects of user identification, authentication and authorisation in a federated system-of-systems environment.

Processing & Chaining (P&C)::
Hosting and maintaining an inventory of all processing tasks, analysis tools and interactive applications. Handles and abstracts the low-level complexities of the different underlying compute technologies, and ensures the compute layer is scaled in accordance with current demand. Provides an integrated development environment to facilitate development of new processing algorithms and applications. Facilitating the network of EO resources by providing a federated interface to other processing services within the wider EO network.

Resource Management (RM)::
Storage and cataloguing of all persistent resources, including data and other supporting material such as documents. Handles and abstracts the low-level complexities of different underlying storage technologies and strategies. Facilitating the network of EO resources by providing a federated interface to other data services within the wider EO network.

In the following subsections we identify functionality that is derived from the use-cases, and then map this onto domain areas.

== User accesses Platform services

[cols="<.^85,^.^5,^.^5,^.^5"]
|===
| Platform Function | UM | P&C | RM

| Each user uniquely identified | x | | 
| User identification/authentication using external Identity Provider | x | | 
| User assigned access privileges to platform resources (data/services) | x | | 
| Unidentified / unauthorised user is regarded as a Guest with limited access | x | | 
| EP enforces authorisation when user accesses platform resources (data/services) | x | | 
| EP accesses resources of other platform on behalf of a user (delegated) | x | | 
| EP enforces authorisation when an external platform attempts delegated access on behalf of a user | x | | 

|===
